//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Craps
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrapsResult
    {
        public int id { get; set; }
        public int userId { get; set; }
        public string gameStatus { get; set; }
        public int rollSum { get; set; }
        public int pointTotal { get; set; }
    }
}
